spring:
  datasource:
    url: ${PERSONAL_DB_URL}
    username: ${PERSONAL_DB_USERNAME}
    password: ${PERSONAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
logging:
  level:
    org:
      springframework:
        security: debug
    java:
      level: error
